'use client';

import { Download } from "lucide-react";
import { Button } from "../ui/button";

export function DownloadSummaryButton({
    summaryText,
    title,
    fileName,
    createdAt
}: {
    summaryText: string;
    title: string;
    fileName: string;
    createdAt: string;
}) {

    const handleDownload = () => {
        const summaryContent = `# ${title}
Generated Summary
Generated On: ${new Date(createdAt).toLocaleDateString()}

${summaryText}

Original File: ${fileName}
Generated By Shortly
        `;

        const blob = new Blob([summaryContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);

        const link = document.createElement('a');
        link.href = url;
        link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`;
        document.body.appendChild(link);
        link.click();

        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    return (
        <Button
            className="h-8 px-3 bg-violet-100 text-violet-600 hover:text-violet-700 hover:bg-violet-50"
            onClick={handleDownload}>
            <Download className="w-4 h-4 mr-1" />
            Download Summary
        </Button>
    )
}